### ISSUE TITLE
Abnormal close detected. Waiting for 2s before reconnect

### ISSUE THREAD

**Issue by Khaldi-Anouar** [Ankr-network/game-unity-sdk#141]
<h4>Hello there, I started using MirageSdk 2 weeks ago, it was working fine before this problem appear when I try to open session.</h4>

![image](https://github.com/Ankr-network/game-unity-sdk/assets/28868733/3adab65c-c814-4903-847b-ecdfa33d9f6d)

<h3>Is there any solution?</h3>

**Comment by defchen** [comment]
nodeinstance.online is just an example link of custom walletconnet bridge server. change it in walletconnect setting so in plugin

**Comment by Vukiz** [comment]
Hello @Khaldi-Anouar , as @defchen mentioned: you have to get a wallet connect bridge instance of your own as noteinstance.online is just an example.
