### ISSUE TITLE
WallectConnect V1 or V2. The bridge servers are v1 only.

### ISSUE THREAD

**Issue by defchen** [Ankr-network/game-unity-sdk#142]
is ankr sdk implemented from WallectConnect V1? The bridge servers are v1 only.

**Comment by Vukiz** [comment]
Hello @defchen
You can check our wallet connect bridge fork that should support v2
https://github.com/Ankr-network/WalletConnectSharp-Fork
Or you can check the original repo if they do support that: https://github.com/WalletConnect/WalletConnectSharp
