### ISSUE TITLE
Facing NullReferenceException at WalletConnectNEthereumExtensions.CreateProvider.

### ISSUE THREAD

**Issue by Afzal-Devstree** [Ankr-network/game-unity-sdk#76]
I am trying to run the Uidemo scene and trying to SignIn but get NullReferenceException at WalletConnectNEthereumExtensions.CreateProvider.

**Comment by Vukiz** [comment]
We are taking a look at that issue.

**Comment by Afzal-Devstree** [comment]
Thanks for your replay, Any other solution for a run this SDK? We need to get all NFT tokens only.

**Comment by Vukiz** [comment]
closing this issue as it should be fixed after our latest refactoring.

**Comment by Vukiz** [comment]
Please ping us if the issue still persists
